name: Trigger Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar webhook de deploy
        env:
          DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }}
        run: |
          curl -X POST https://csapp.prolinx.com.br/deploy \
               -H "Authorization: Bearer $DEPLOY_SECRET"
